Convert app to use Go modules
ONSdigital/dp-file-downloader pull request #16
Opened 2020-10-26 12:16 UTC by jondewijones

- Converted to Go modules
- Replaced project specific health check package with dp-healthcheck
- Switched to /health for health check
- Replaced logger with log.go/log
- Replaced go-ns/server with dp-net/http server
- Moved main from cmd to root as per other services
- Updated api_tests to include a healthcheck mock
- Updated Makefile to include necessary fields for health check initialisation

2020-10-26 13:03 UTC, nshumoogum requested changes

2020-10-26 13:03 UTC, nshumoogum commented on README.md
> +| HEALTHCHECK_INTERVAL           | Interval between health checks                                                            |    30 seconds |
The description and default value are in the wrong columns for both `HEALTHCHECK_INTERVAL` and `HEALTHCHECK_CRITICAL_TIMEOUT`

2020-10-26 13:03 UTC, nshumoogum commented on clients/table-renderer/client.go
> +package table_renderer
Should this package really be in the `dp-api-clients-go` repository?

2020-10-26 13:03 UTC, nshumoogum commented on cmd/dp-file-downloader/main.go
> +	table_renderer "github.com/ONSdigital/dp-file-downloader/clients/table-renderer"
this should be referred to as `tableRenderer`

2020-10-26 13:03 UTC, nshumoogum commented on cmd/dp-file-downloader/main.go
> +	tabrend := table_renderer.New(cfg.TableRendererHost)
We should be using camel case, `tableRenderer` instead of snake case `table_renderer`

2020-10-26 13:03 UTC, nshumoogum commented on table/table_test.go
> +			spew.Dump("RESPONSE >>>>", expectedResponse)
Probably want to remove this line and remove dependency from this test package

2020-10-26 13:03 UTC, nshumoogum commented on config/config.go
> +		APIRouterURL:               "http://localhost:23200/v1",
Should this have `/v1` appended to the end?

2020-10-26 13:21 UTC, jondewijones commented on table/table_test.go
> +			spew.Dump("RESPONSE >>>>", expectedResponse)
👍

2020-10-26 13:21 UTC, jondewijones commented on cmd/dp-file-downloader/main.go
> +	tabrend := table_renderer.New(cfg.TableRendererHost)
👍

2020-10-26 13:21 UTC, jondewijones commented on cmd/dp-file-downloader/main.go
> +	table_renderer "github.com/ONSdigital/dp-file-downloader/clients/table-renderer"
👍

2020-10-26 13:22 UTC, jondewijones commented on README.md
> +| HEALTHCHECK_INTERVAL           | Interval between health checks                                                            |    30 seconds |
👍

2020-10-26 13:41 UTC, nshumoogum commented on ci/unit.yml
>    path: dp-file-downloader/ci/scripts/audit.sh
This should be `.../unit.sh` instead of `.../audit.sh`

2020-10-26 13:42 UTC, nshumoogum commented on ci/build.yml
> +  path: dp-file-downloader/ci/scripts/audit.sh
This should be `.../build.sh` instead of `.../audit.sh`

2020-10-26 14:03 UTC, jondewijones commented on clients/table-renderer/client.go
> +package table_renderer
When we (@janderson2 ) discussed the task initially we decided/agreed it made sense to build it in the app

2020-10-27 11:24 UTC, nshumoogum commented on config/config.go
> +		APIRouterURL:               "http://localhost:23200/v1",
Checked with James and this is correct default value for APIRouterURL

2020-10-27 13:51 UTC, nshumoogum approved these changes

2020-10-27 20:09 UTC, merged